"""Concatenate manual sections + render to PDF via pandoc.

Pipeline:

  manual/*.md (sorted alphanumerically)
    └─ assembled into build/tui-user-manual.md (page-break-separated)
       └─ pandoc → build/tui-user-manual.pdf

Section ordering follows the numeric prefix (Python's ``sorted`` over
``Path.glob`` is alphanumeric and stable):

  00-intro.md           → front matter
  10-catalog-*.md       → reference catalogs (auto-generated by inventory)
  20-walkthrough-*.md   → per-feature walkthroughs (driven by walker)
  99-outro.md           → appendix

Page breaks
-----------
A LaTeX ``\\newpage`` directive is inserted between every consecutive
pair of sections so each feature starts on a fresh page.  Pandoc passes
raw LaTeX through unmodified when the output engine is xelatex.

Fonts
-----
The TUI scene captures use heavy Unicode box-drawing characters
(``╭ ╰ ─ │ ╯``).  The default LaTeX mono font (``lmmono10``) doesn't
cover them and pandoc emits "Missing character" warnings.  We force
``DejaVu Sans Mono`` as the mono font (full BMP coverage, included in
most distros under ``fonts-dejavu`` / ``fonts-dejavu-core``).  When the
font is absent the run falls back to pandoc's default with the warnings
re-enabled — operator can install ``fonts-dejavu-core`` to clean up.

Eisvogel template (optional polish)
-----------------------------------
If ``~/.pandoc/templates/eisvogel.latex`` exists, it's used to give the
PDF a polished "professional manual" look (running headers, color-coded
code blocks, title page).  Absence falls back to pandoc's default LaTeX
template — works fine, just less pretty.  Install via:

    mkdir -p ~/.pandoc/templates && cd ~/.pandoc/templates && \\
      curl -L -o eisvogel.latex \\
        https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex
"""

import shutil
import subprocess
from datetime import date
from pathlib import Path
from typing import List


PAGE_BREAK = "\n\n\\newpage\n\n"

DEFAULT_TITLE = "jaato TUI — User Manual"
DEFAULT_SUBTITLE = "Generated by the jaato-tui-driven-tests harness"

# Per-Unicode-block font fallback for glyphs that DejaVu Sans Mono
# doesn't carry (xelatex via the `ucharclasses` package).  The TUI
# scene captures contain:
#
#   • Braille block (U+2800–U+28FF) — the spinner ⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏
#   • Misc symbols + pictographs (U+1F300–U+1F5FF) — the lock 🔒
#
# We route those two blocks to fonts known to cover them: Braille →
# DejaVu Sans (already on disk for our sansfont), pictographs → FreeMono
# (B&W, monospaced, aligns with the rest of the box-drawing).  Any
# future glyph from the same blocks is handled automatically — no
# per-codepoint declarations needed.
HEADER_INCLUDES_FONT_FALLBACK = r"""\usepackage[BraillePatterns,MiscellaneousSymbolsAndPictographs]{ucharclasses}
\newfontfamily\fallbacksans{DejaVu Sans}
\newfontfamily\fallbackpict{FreeMono}
\setTransitionTo{BraillePatterns}{\fallbacksans}
\setTransitionFrom{BraillePatterns}{\normalfont}
\setTransitionTo{MiscellaneousSymbolsAndPictographs}{\fallbackpict}
\setTransitionFrom{MiscellaneousSymbolsAndPictographs}{\normalfont}
"""


class PDFBuilder:
    def __init__(self, manual_dir: Path, build_dir: Path):
        self._manual_dir = manual_dir
        self._build_dir = build_dir

    # ------------------------------------------------------------------
    # Public entry
    # ------------------------------------------------------------------

    def run(self) -> None:
        sections = sorted(self._manual_dir.glob("*.md"))
        if not sections:
            raise RuntimeError(
                f"No .md sections in {self._manual_dir} — run "
                "`python -m harness inventory` and `... walk` first."
            )

        assembled_md = self._assemble_markdown(sections)
        print(
            f"  ✓ markdown assembled ({len(sections)} sections): "
            f"{assembled_md.name}"
        )

        if not shutil.which("pandoc"):
            print(
                "  ! pandoc not on PATH — markdown only; install pandoc for PDF"
            )
            return

        pdf_path = self._build_dir / "tui-user-manual.pdf"
        cmd = self._build_pandoc_cmd(assembled_md, pdf_path)
        self._run_pandoc(cmd, assembled_md, pdf_path)

    # ------------------------------------------------------------------
    # Assembly
    # ------------------------------------------------------------------

    def _assemble_markdown(self, sections: List[Path]) -> Path:
        """Concatenate sections with a LaTeX page break between each."""
        assembled_md = self._build_dir / "tui-user-manual.md"
        body = PAGE_BREAK.join(p.read_text() for p in sections)
        assembled_md.write_text(body)
        return assembled_md

    # ------------------------------------------------------------------
    # Pandoc invocation
    # ------------------------------------------------------------------

    def _build_pandoc_cmd(self, src: Path, dst: Path) -> List[str]:
        cmd: List[str] = [
            "pandoc", str(src),
            "-o", str(dst),
            "--toc",
            "--toc-depth=2",
            # Title-page metadata.  Eisvogel (when present) renders a
            # full title page from these; default template puts them
            # in the header area.
            "-V", f"title={DEFAULT_TITLE}",
            "-V", f"subtitle={DEFAULT_SUBTITLE}",
            "-V", f"date={date.today().isoformat()}",
            # Page geometry (sensible defaults for an end-user manual).
            "-V", "geometry=margin=1in",
            "-V", "papersize=a4",
            # Hyperlink theming so the ToC is visible but not garish.
            "-V", "colorlinks=true",
            "-V", "linkcolor=NavyBlue",
            "-V", "urlcolor=NavyBlue",
            "-V", "toccolor=NavyBlue",
        ]

        # Pick a mono font with full Unicode box-drawing support so TUI
        # scene captures render without "Missing character" warnings.
        if self._fontconfig_has("DejaVu Sans Mono"):
            cmd.extend([
                "-V", "monofont=DejaVu Sans Mono",
                "-V", "mainfont=DejaVu Serif",
                "-V", "sansfont=DejaVu Sans",
            ])

        # Per-Unicode-block fallback for spinner + emoji glyphs.  Only
        # applied when the supporting fonts are present — without them
        # ucharclasses would crash xelatex with a missing-font error.
        if (self._fontconfig_has("DejaVu Sans")
                and self._fontconfig_has("FreeMono")):
            cmd.extend([
                "--variable", f"header-includes={HEADER_INCLUDES_FONT_FALLBACK}",
            ])

        # Eisvogel template if available — gives a pro-document look.
        eisvogel = Path.home() / ".pandoc" / "templates" / "eisvogel.latex"
        if eisvogel.is_file():
            cmd.extend(["--template=eisvogel"])

        # xelatex required for our font + Unicode setup.
        if shutil.which("xelatex"):
            cmd.extend(["--pdf-engine=xelatex"])

        return cmd

    def _run_pandoc(
        self, cmd: List[str], src: Path, dst: Path,
    ) -> None:
        try:
            result = subprocess.run(
                cmd, check=True, capture_output=True, text=True,
            )
        except subprocess.CalledProcessError as exc:
            print(
                f"  ! pandoc exited {exc.returncode} — markdown is at "
                f"{src.name}; rerun pandoc manually for diagnostics:"
            )
            for line in (exc.stderr or "").splitlines()[-10:]:
                print(f"      {line}")
            return

        # Filter pandoc warnings into a small summary instead of dumping
        # the raw stream — keeps the operator's terminal readable.
        missing_char_warnings = sum(
            1 for line in (result.stderr or "").splitlines()
            if "Missing character" in line
        )
        if missing_char_warnings:
            print(
                f"  · {missing_char_warnings} 'Missing character' "
                f"warnings (font coverage gaps; install fonts-dejavu-core)"
            )

        size_kb = dst.stat().st_size / 1024
        print(f"  ✓ PDF ({size_kb:.0f} KB): {dst.name}")

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _fontconfig_has(family: str) -> bool:
        """True when fontconfig knows about a font family by name."""
        if not shutil.which("fc-list"):
            return False
        try:
            out = subprocess.run(
                ["fc-list", ":family"], capture_output=True, text=True,
                timeout=5, check=False,
            )
        except (subprocess.SubprocessError, OSError):
            return False
        return family.lower() in out.stdout.lower()
