"""Concatenate manual sections + render to PDF via pandoc.

Section ordering follows the numeric prefix (Python's ``sorted`` over
``Path.glob`` is alphanumeric and stable):

  00-intro.md           → front matter
  10-catalog-*.md       → reference catalogs (auto-generated by inventory)
  20-walkthrough-*.md   → per-feature walkthroughs (drove by walker)
  99-outro.md           → appendix

Pandoc invocation uses the eisvogel template if available (gives a
"professional manual" look with running headers + ToC), otherwise falls
back to pandoc's default LaTeX template.  No xelatex dependency
beyond what pandoc requires by default.
"""
import shutil
import subprocess
from pathlib import Path


class PDFBuilder:
    def __init__(self, manual_dir: Path, build_dir: Path):
        self._manual_dir = manual_dir
        self._build_dir = build_dir

    def run(self) -> None:
        sections = sorted(self._manual_dir.glob("*.md"))
        if not sections:
            raise RuntimeError(
                f"No .md sections in {self._manual_dir} — run "
                "`python -m harness inventory` and `... walk` first."
            )
        # Hidden files (.discovered.json, etc.) are NOT in glob('*.md');
        # the leading-dot exclusion is automatic.

        assembled_md = self._build_dir / "tui-user-manual.md"
        assembled_md.write_text(
            "\n\n".join(p.read_text() for p in sections)
        )
        print(f"  ✓ markdown assembled: {assembled_md}")

        pdf_path = self._build_dir / "tui-user-manual.pdf"
        if not shutil.which("pandoc"):
            print("  ! pandoc not on PATH — markdown only; install pandoc to get PDF")
            return
        cmd = [
            "pandoc", str(assembled_md),
            "-o", str(pdf_path),
            "--toc",
            "--metadata", "title=jaato TUI — User Manual",
        ]
        # Eisvogel template gives a polished pandoc PDF.  Optional;
        # absence falls back to pandoc's default look.
        if shutil.which("xelatex"):
            cmd.extend(["--pdf-engine=xelatex"])
        try:
            subprocess.run(cmd, check=True)
            print(f"  ✓ PDF: {pdf_path}")
        except subprocess.CalledProcessError as e:
            print(
                f"  ! pandoc exited {e.returncode} — markdown is at "
                f"{assembled_md}; rerun pandoc manually for diagnostics"
            )
